#!/bin/bash

sudo yum update -y
sudo yum install java-1.8.0-openjdk -y
sudo yum remove java-1.7.0-openjdk -y

wget -O ftb.zip https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/files/2418192/download
unzip ftb.zip
chmod 700 FTBInstall.sh
chmod 700 ServerStart.sh
echo "eula=true" > eula.txt

aws s3 cp --recursive s3://leone-ftb-server/worlds .

screen -S ftbScreen -dm ./ServerStart.sh

